import type { Metadata } from "next";
import { Encode_Sans } from "next/font/google";
import "../../node_modules/@fortawesome/fontawesome-free/css/all.css";
import "slick-carousel/slick/slick.css";
import "slick-carousel/slick/slick-theme.css";
import { Toaster } from "@/components/ui/sonner"
import "./globals.css";
import Navbar from "./_Component/Navbar/Navbar";
import UserProvider from "../UserProvider";
import CountProvider from "../CountProvider";



 
const Encode_SansFont = Encode_Sans({
  subsets:["latin"],
  weight:["100",'500','900']
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${Encode_SansFont.className}`} >


      <UserProvider>
      <CountProvider>

        <Navbar/>
        <main  className= ' italic  p-4'>
        {children}
        </main>
        <Toaster/>

      </CountProvider>

      </UserProvider>
      </body>
    </html>
  );
}
